version: '3'
services:
  frontend:
    build: ./client
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./client/dist:/var/www
    depends_on:
      - backend
  backend:
    build: ./server
    command: npm start
    expose:
      - "80"
    # ports:
    #   - "80:80"
    volumes:
      - ./server:/usr/app
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/couplegoals
      - PORT=80
    depends_on:
      - db
  db:
    image: postgres:latest
    # ports:
    #   - "5432:5432"