version: '3'
services:
  db:
    # TODO: In the first init the database is not created and the backend service will fail to apply the migration. Running a second time when the database is already created will solve it. Find a way to fix this and not rely in a second run
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=couplegoals
  backend:
    build: ./server
    command: npm run start:dev
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/couplegoals
      - DATABASE_HOST=db
      - DATABASE_NAME=couplegoals
      - PORT=3000
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./server:/code
  # frontend:
  #   build: ./client
  #   expose:
  #     - "80"
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./client/dist:/var/www
  #   environment:
  #     - BACKEND_URL=http://localhost:3000
  #   depends_on:
  #     - backend
  